services:
  twingate-client-http-proxy:
    image: ghcr.io/casta-mere/twingate-client-http-proxy:latest
    container_name: twingate-client-http-proxy
    restart: unless-stopped
    ports:
      - "7575:9999"
      - "7576:8080"
